### ISSUE TITLE
Entry not run on CreateInitialState.

### ISSUE THREAD

**Issue by kimsDK** [canton7/StateMechanic#6]
Wonder why Entry is not run when Entering initial state.
In the Quantum HSM the initial state is set, but first transittion into it, when running init() on the hsm, make the Entry code run for the Initial state.
Is this by design? - or a missing feature (bug).
I am aware that it may not be a good idea to run Enter when creating the initial state.

In UML the initial state is entered from unknown (a black dot). It can be argued if it is a transition, because it come from unkown (no state).

BR Kim

**Comment by canton7** [comment]
It's by design. Let's say you have an entry handler for the initial state: what would the 'from' state be? What would the event or eventdata be? 

You can always start your state machine by firing some sort of "reset" event, which transitions you from your initial state into your first state.

**Comment by kimsDK** [comment]
Ok so CreateInitialState() is like UML "Initial" (the black dot).
It just confused me, that it is created like a normal state type, that is possible to do Entry and Exit.
In the Quantum HSM it automatic enter the "Initial" and by calling the init() on the state event machine then do the transition into first state, running Entry on the first state.
I just have objection, that you can transition from other states into "Initial" state in your implementation, and the Entry is actually run then.
The transition from "Initial" to the first state, is one way (in UML the black dot with one transition into the stateeventmachine first state) - besides that, good job :-)
BR Kim

**Comment by canton7** [comment]
> I just have objection, that you can transition from other states into "Initial" state in your implementation, and the Entry is actually run then.

Yes, again that is by design.

The initial state is simply the state that the state machine starts in. All states are equal, but when the state machine is created (or reset), the current state is set to the initial state. That's all. It's simple.

You can choose to make that a UML "black dot" state (by not defining any handlers for it, or transitions into it) if you want, or you can choose to make it a normal state that the state machine happens to start in. The choice is yours.

**Comment by canton7** [comment]
Closing as no response
